language: python
python:
  - "3.6"

cache: pip

# command to install dependencies
#install: pip install -r requirements.txt
install:
  - pip install coveralls
  - pip install coverage
  - pip install flask

env:
CODECLIMATE_REPO_TOKEN: 15900a5efb7df2332a727a2484ae85eedebfdbfd2d1cccc7a6be2c5bc2e055ca

# command to run tests
script:
  - nosetests --with-coverage --cover-package=app

after_success: coveralls
